# Generated by Django 5.0.7 on 2024-07-22 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorderauthapp', '0002_alter_restaurantowner_user'),
        ('restaurantownerapp', '0002_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='restaurantownerapp.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='foodorderauthapp.restaurantowner'),
        ),
    ]
