# Generated by Django 5.0.7 on 2024-07-19 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorderauthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_owner_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
