# Generated by Django 5.0.7 on 2024-07-19 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordersapp', '0001_initial'),
        ('restaurantownerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurantownerapp.menu'),
        ),
    ]
