# Generated by Django 5.0.7 on 2024-07-22 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorderauthapp', '0002_alter_restaurantowner_user'),
        ('ordersapp', '0002_initial'),
        ('restaurantownerapp', '0003_alter_menu_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodorderauthapp.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='restaurantownerapp.menu'),
        ),
    ]
